/* tslint:disable */
/* eslint-disable */
/**
 * nemesis-backend API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */export * from './apis/admin-service-api';
export * from './apis/client-service-api';
export * from './apis/employee-service-api';
export * from './apis/example-resource-api';
export * from './apis/partner-service-api';
export * from './apis/user-service-api';

