import { ClientDto, GenericPersonDto } from "../gen";

export const createEmptyGenericPersonDto = () : GenericPersonDto => { return {
  firstName: '',
  lastName: '',
  email: '',
  phone: '',
  mobile: '',
  title: '',
  academicDegree: '',
  birthday: '',
  birthPlace: '',
  nationality: null,
  socialInsuranceInstitution: null,
  occupation: '',
  country: null,
  zipCode: '',
  city: '',
  address: '',
}}

export const createEmptyClientDto = () : ClientDto => { return {
  firstName: '',
  lastName: '',
  email: '',
  phone: '',
  mobile: '',
  title: '',
  academicDegree: '',
  birthday: '',
  birthPlace: '',
  nationality: undefined,
  socialInsuranceInstitution: undefined,
  occupation: '',
  country: undefined,
  zipCode: '',
  city: '',
  address: '',
  supervisor: '',
  deleted: false,
  militaryServiceDone: false,
  smoker: false,
  pets: false,
  petsRemarks: '',
  maritalStatus: undefined,
  homeRemarks: '',
  bank: '',
  iban: '',
  bic: '',
  partner: undefined,
  children: [],
  contracts: [],
  documents: [],
  proofOfIdentities: [],
}}

