import { ClientDto, GenericPersonDto } from "../gen";

export let emptyGenericPersonDto: GenericPersonDto = {
  firstName: '',
  lastName: '',
  email: '',
  phone: '',
  mobile: '',
  title: '',
  academicDegree: '',
  birthday: '',
  birthPlace: '',
  nationality: null,
  socialInsuranceInstitution: null,
  occupation: '',
  country: null,
  zipCode: '',
  city: '',
  address: '',
}

export let emptyClientDto: ClientDto = {
  firstName: '',
  lastName: '',
  email: '',
  phone: '',
  mobile: '',
  title: '',
  academicDegree: '',
  birthday: '',
  birthPlace: '',
  nationality: null,
  socialInsuranceInstitution: null,
  occupation: '',
  country: null,
  zipCode: '',
  city: '',
  address: '',
  supervisor: '',
  deleted: false,
  militaryServiceDone: false,
  smoker: false,
  pets: false,
  petsRemarks: '',
  maritalStatus: null,
  homeRemarks: '',
  bank: '',
  iban: '',
  bic: '',
  partner: emptyGenericPersonDto,
  children: [],
  contracts: [],
  documents: [],
  proofOfIdentities: [],
}

