/* tslint:disable */
/* eslint-disable */
/**
 * nemesis-backend API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { Employee } from '../models';
/**
 * EmployeeServiceApi - axios parameter creator
 * @export
 */
export const EmployeeServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {Employee} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEmployeeAddPost: async (body?: Employee, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/employee/add`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEmployeeListGet: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/employee/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {Employee} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEmployeeUpdatePost: async (body?: Employee, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/employee/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EmployeeServiceApi - functional programming interface
 * @export
 */
export const EmployeeServiceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {Employee} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEmployeeAddPost(body?: Employee, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await EmployeeServiceApiAxiosParamCreator(configuration).apiEmployeeAddPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEmployeeListGet(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Employee>>> {
            const localVarAxiosArgs = await EmployeeServiceApiAxiosParamCreator(configuration).apiEmployeeListGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {Employee} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEmployeeUpdatePost(body?: Employee, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await EmployeeServiceApiAxiosParamCreator(configuration).apiEmployeeUpdatePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * EmployeeServiceApi - factory interface
 * @export
 */
export const EmployeeServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {Employee} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEmployeeAddPost(body?: Employee, options?: any): AxiosPromise<void> {
            return EmployeeServiceApiFp(configuration).apiEmployeeAddPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEmployeeListGet(options?: any): AxiosPromise<Array<Employee>> {
            return EmployeeServiceApiFp(configuration).apiEmployeeListGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {Employee} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEmployeeUpdatePost(body?: Employee, options?: any): AxiosPromise<void> {
            return EmployeeServiceApiFp(configuration).apiEmployeeUpdatePost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EmployeeServiceApi - object-oriented interface
 * @export
 * @class EmployeeServiceApi
 * @extends {BaseAPI}
 */
export class EmployeeServiceApi extends BaseAPI {
    /**
     * 
     * @param {Employee} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeServiceApi
     */
    public apiEmployeeAddPost(body?: Employee, options?: any) {
        return EmployeeServiceApiFp(this.configuration).apiEmployeeAddPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeServiceApi
     */
    public apiEmployeeListGet(options?: any) {
        return EmployeeServiceApiFp(this.configuration).apiEmployeeListGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {Employee} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeServiceApi
     */
    public apiEmployeeUpdatePost(body?: Employee, options?: any) {
        return EmployeeServiceApiFp(this.configuration).apiEmployeeUpdatePost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
