/* tslint:disable */
/* eslint-disable */
/**
 * nemesis-backend API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Client
 */
export interface Client {
    /**
     * 
     * @type {number}
     * @memberof Client
     */
    id?: any;
    /**
     * 
     * @type {Date}
     * @memberof Client
     */
    createdAt?: any;
    /**
     * 
     * @type {Gender}
     * @memberof Client
     */
    gender?: any;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    firstName?: any;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    lastName?: any;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    email?: any;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    phone?: any;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    mobile?: any;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    title?: any;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    academicDegree?: any;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    birthday?: any;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    birthPlace?: any;
    /**
     * 
     * @type {Country}
     * @memberof Client
     */
    nationality?: any;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    socialInsuranceInstitution?: any;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    occupation?: any;
    /**
     * 
     * @type {Country}
     * @memberof Client
     */
    country?: any;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    zipCode?: any;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    city?: any;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    address?: any;
    /**
     * 
     * @type {Employee}
     * @memberof Client
     */
    supervisor?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Client
     */
    deleted?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Client
     */
    militaryServiceDone?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Client
     */
    smoker?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Client
     */
    pets?: any;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    petsRemarks?: any;
    /**
     * 
     * @type {MaritalStatus}
     * @memberof Client
     */
    maritalStatus?: any;
    /**
     * 
     * @type {GenericPerson}
     * @memberof Client
     */
    partner?: any;
    /**
     * 
     * @type {Array&lt;GenericPerson&gt;}
     * @memberof Client
     */
    children?: any;
    /**
     * 
     * @type {Array&lt;Contract&gt;}
     * @memberof Client
     */
    contracts?: any;
    /**
     * 
     * @type {Array&lt;ProofOfIdentity&gt;}
     * @memberof Client
     */
    proofOfIdentities?: any;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    bank?: any;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    iban?: any;
    /**
     * 
     * @type {string}
     * @memberof Client
     */
    bic?: any;
}
