/* tslint:disable */
/* eslint-disable */
/**
 * nemesis-backend API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GenericPerson
 */
export interface GenericPerson {
    /**
     * 
     * @type {number}
     * @memberof GenericPerson
     */
    id?: any;
    /**
     * 
     * @type {Date}
     * @memberof GenericPerson
     */
    createdAt?: any;
    /**
     * 
     * @type {Gender}
     * @memberof GenericPerson
     */
    gender?: any;
    /**
     * 
     * @type {string}
     * @memberof GenericPerson
     */
    firstName?: any;
    /**
     * 
     * @type {string}
     * @memberof GenericPerson
     */
    lastName?: any;
    /**
     * 
     * @type {string}
     * @memberof GenericPerson
     */
    email?: any;
    /**
     * 
     * @type {string}
     * @memberof GenericPerson
     */
    phone?: any;
    /**
     * 
     * @type {string}
     * @memberof GenericPerson
     */
    mobile?: any;
    /**
     * 
     * @type {string}
     * @memberof GenericPerson
     */
    title?: any;
    /**
     * 
     * @type {string}
     * @memberof GenericPerson
     */
    academicDegree?: any;
    /**
     * 
     * @type {string}
     * @memberof GenericPerson
     */
    birthday?: any;
    /**
     * 
     * @type {string}
     * @memberof GenericPerson
     */
    birthPlace?: any;
    /**
     * 
     * @type {Country}
     * @memberof GenericPerson
     */
    nationality?: any;
    /**
     * 
     * @type {string}
     * @memberof GenericPerson
     */
    socialInsuranceInstitution?: any;
    /**
     * 
     * @type {string}
     * @memberof GenericPerson
     */
    occupation?: any;
    /**
     * 
     * @type {Country}
     * @memberof GenericPerson
     */
    country?: any;
    /**
     * 
     * @type {string}
     * @memberof GenericPerson
     */
    zipCode?: any;
    /**
     * 
     * @type {string}
     * @memberof GenericPerson
     */
    city?: any;
    /**
     * 
     * @type {string}
     * @memberof GenericPerson
     */
    address?: any;
}
