/* tslint:disable */
/* eslint-disable */
/**
 * nemesis-backend API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PartnerLogin
 */
export interface PartnerLogin {
    /**
     * 
     * @type {number}
     * @memberof PartnerLogin
     */
    id?: any;
    /**
     * 
     * @type {Date}
     * @memberof PartnerLogin
     */
    createdAt?: any;
    /**
     * 
     * @type {string}
     * @memberof PartnerLogin
     */
    link?: any;
    /**
     * 
     * @type {string}
     * @memberof PartnerLogin
     */
    username?: any;
    /**
     * 
     * @type {string}
     * @memberof PartnerLogin
     */
    password?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PartnerLogin
     */
    adminOnly?: any;
}
