/* tslint:disable */
/* eslint-disable */
/**
 * nemesis-backend API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PartnerServiceType
 */
export interface PartnerServiceType {
    /**
     * 
     * @type {number}
     * @memberof PartnerServiceType
     */
    id?: any;
    /**
     * 
     * @type {Date}
     * @memberof PartnerServiceType
     */
    createdAt?: any;
    /**
     * 
     * @type {string}
     * @memberof PartnerServiceType
     */
    service?: any;
}
