/* tslint:disable */
/* eslint-disable */
/**
 * nemesis-backend API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PartnerContact
 */
export interface PartnerContact {
    /**
     * 
     * @type {number}
     * @memberof PartnerContact
     */
    id?: any;
    /**
     * 
     * @type {Date}
     * @memberof PartnerContact
     */
    createdAt?: any;
    /**
     * 
     * @type {string}
     * @memberof PartnerContact
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof PartnerContact
     */
    email?: any;
    /**
     * 
     * @type {string}
     * @memberof PartnerContact
     */
    phone?: any;
    /**
     * 
     * @type {string}
     * @memberof PartnerContact
     */
    remarks?: any;
}
