/* tslint:disable */
/* eslint-disable */
/**
 * nemesis-backend API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Partner
 */
export interface Partner {
    /**
     * 
     * @type {number}
     * @memberof Partner
     */
    id?: any;
    /**
     * 
     * @type {Date}
     * @memberof Partner
     */
    createdAt?: any;
    /**
     * 
     * @type {string}
     * @memberof Partner
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof Partner
     */
    website?: any;
    /**
     * 
     * @type {string}
     * @memberof Partner
     */
    bank?: any;
    /**
     * 
     * @type {string}
     * @memberof Partner
     */
    iban?: any;
    /**
     * 
     * @type {string}
     * @memberof Partner
     */
    bic?: any;
    /**
     * 
     * @type {Array&lt;PartnerContact&gt;}
     * @memberof Partner
     */
    contacts?: any;
    /**
     * 
     * @type {Array&lt;PartnerLogin&gt;}
     * @memberof Partner
     */
    logins?: any;
    /**
     * 
     * @type {Array&lt;PartnerServiceType&gt;}
     * @memberof Partner
     */
    services?: any;
}
